import { useState } from 'react';
import type * as React from 'react';
import { badges, levels, missionDefinitions } from '../data/gamification';
import { useLearning } from '../state/LearningContext';
import { missionCounts } from '../state/gamification';
import type { Navigate, Page } from '../types';
import { Icon, Modal, PageHeading, ProgressBar, SectionHeading } from '../components/ui';

export function AchievementsPage({ navigate, missions = false }: { navigate: Navigate; missions?: boolean }) {
  const { progress } = useLearning();
  const [selectedBadge, setSelectedBadge] = useState<string | null>(null);
  const selected = badges.find((badge) => badge.id === selectedBadge);
  const counts = missionCounts(progress);
  const targets: { page: Page; id?: string }[] = [{ page: 'materials', id: '1' }, { page: 'planets' }, { page: 'materials' }, { page: 'games', id: 'order' }, { page: 'quiz' }];
  return <div><PageHeading eyebrow="SETIAP USAHA BERARTI" title={missions ? 'Peta misi penjelajah.' : 'Pencapaian saya.'} description={missions ? 'Lima misi untuk perjalanan belajar yang utuh. Selesaikan satu demi satu.' : 'Bukan hanya badge. Ini jejak rasa ingin tahu dan usaha belajarmu.'} action={progress.missions.length === 5 ? <button className="button primary" onClick={() => navigate('complete')}><Icon name="trophy" />Lihat hasil perjalanan</button> : undefined} /><div className="achievements-tabs filter-tabs"><button className={!missions ? 'active' : ''} onClick={() => navigate('achievements')} aria-pressed={!missions}><Icon name="award" size={17} />Badge saya <span>{progress.badges.length}/5</span></button><button className={missions ? 'active' : ''} onClick={() => navigate('achievements', 'missions')} aria-pressed={missions}><Icon name="target" size={17} />Misi belajar <span>{progress.missions.length}/5</span></button></div>
    {missions ? <div className="mission-list">{missionDefinitions.map((mission, index) => {
      const done = progress.missions.includes(mission.id);
      return <div className={`mission-row ${done ? 'done' : ''}`} key={mission.id}><span className="mission-step-number">{done ? <Icon name="check" size={26} /> : String(index + 1).padStart(2, '0')}</span><div className="mission-row-content"><div className="mission-row-title"><p className="eyebrow">MISSION {String(index + 1).padStart(2, '0')}</p><span className="xp-label"><Icon name="zap" size={14} />+50 XP</span></div><h2>{mission.name}</h2><p>{mission.description}</p><div className="mission-progress-line"><ProgressBar value={counts[index] / mission.target * 100} label={`Progres ${mission.name}`} /><span>{counts[index]}/{mission.target} {mission.unit}</span></div></div><button className={`button ${done ? 'secondary' : 'primary'}`} onClick={() => navigate(targets[index].page, targets[index].id)}>{done ? 'Kunjungi lagi' : 'Mulai misi'}<Icon name={done ? 'reset' : 'right'} size={17} /></button></div>;
    })}</div> : <><div className="badge-grid">{badges.map((badge) => {
      const unlocked = progress.badges.includes(badge.id);
      return <button key={badge.id} className={`badge-item ${unlocked ? 'unlocked' : 'locked'}`} onClick={() => setSelectedBadge(badge.id)}><span className="badge-medallion" style={{ '--badge-color': badge.color } as React.CSSProperties}><span className="badge-inner"><Icon name={badge.icon} size={40} /></span>{!unlocked && <span className="badge-lock"><Icon name="lock" size={14} /></span>}</span><h2>{badge.name}</h2><p>{badge.description}</p><span className="badge-state"><Icon name={unlocked ? 'check' : 'lock'} size={13} />{unlocked ? 'Berhasil diraih' : 'Belum terbuka'}</span></button>;
    })}</div><SectionHeading title="Dari kadet menuju master" description="Levelmu tumbuh bersama setiap kegiatan belajar." /><div className="level-ladder">{levels.map((level) => <div key={level.level} className={progress.level >= level.level ? 'reached' : ''}><span><Icon name={progress.level > level.level ? 'check' : level.level === 4 ? 'trophy' : 'rocket'} size={24} /></span><small>LEVEL {level.level}</small><strong>{level.name}</strong><p>{level.min} XP</p></div>)}</div><details className="xp-explainer"><summary><Icon name="zap" size={18} />Bagaimana cara mendapatkan XP?<Icon name="chevron-down" size={17} /></summary><div>{[['Pelajari planet baru', '+10 XP'], ['Selesaikan materi', '+20 XP'], ['Jawab kuis dengan benar', '+10 XP'], ['Selesaikan mini game', '+30 XP'], ['Selesaikan misi', '+50 XP']].map(([label, value]) => <p key={label}><span>{label}</span><strong>{value}</strong></p>)}<small>Planet, materi, mini game, dan misi memberi XP pada penyelesaian pertama. Kuis memberi XP untuk jawaban benar pada setiap sesi.</small></div></details></>}
    <Modal open={!!selected} onClose={() => setSelectedBadge(null)} title={selected?.name ?? 'Detail badge'}>{selected && <div className="badge-modal-content"><div className={`badge-item ${progress.badges.includes(selected.id) ? 'unlocked' : 'locked'}`}><span className="badge-medallion" style={{ '--badge-color': selected.color } as React.CSSProperties}><span className="badge-inner"><Icon name={selected.icon} size={47} /></span></span></div><h3>{progress.badges.includes(selected.id) ? 'Badge ini milikmu!' : 'Petualangan berikutnya menantimu.'}</h3><p>{selected.description}</p><button className="button primary" onClick={() => { setSelectedBadge(null); navigate('achievements', 'missions'); }}>Lihat misi belajar<Icon name="right" size={17} /></button></div>}</Modal>
  </div>;
}