import { badges, levelForXP } from '../data/gamification';
import { useLearning } from '../state/LearningContext';
import type { Navigate } from '../types';
import { Astronaut, Icon, ProgressBar } from '../components/ui';

export function CompletePage({ navigate }: { navigate: Navigate }) {
  const { progress } = useLearning();
  if (progress.missions.length < 5) return <div className="result-page"><Astronaut className="completion-astronaut" /><p className="eyebrow">PETUALANGAN BELUM BERAKHIR</p><h1>Masih ada dunia untuk ditemukan.</h1><p>Selesaikan lima misi utama untuk menuntaskan perjalanan belajarmu.</p><div className="complete-progress"><ProgressBar value={progress.missions.length / 5 * 100} label="Progres misi utama" /><span>{progress.missions.length} / 5 misi selesai</span></div><button className="button primary" onClick={() => navigate('achievements', 'missions')}>Lanjutkan misiku<Icon name="right" /></button></div>;
  return <div className="complete-page result-page"><div className="completion-illustration"><div className="completion-ring" /><Astronaut className="completion-astronaut" /><span className="completion-star star-one"><Icon name="star" size={30} /></span><span className="completion-star star-two"><Icon name="sparkles" size={40} /></span></div><p className="eyebrow">SELURUH MISI UTAMA SELESAI</p><h1>MISSION COMPLETE!</h1><h2>Selamat, {progress.nickname}!</h2><p>Kamu telah menyelesaikan perjalanan belajar Tata Surya.<br />Teruslah bertanya. Semesta masih menyimpan banyak keajaiban.</p><div className="completion-stats"><div><strong>{progress.xp}</strong><span>Total XP</span></div><div><strong>{progress.level}</strong><span>{levelForXP(progress.xp).name}</span></div><div><strong>{progress.badges.length}</strong><span>Badge diraih</span></div><div><strong>{progress.bestQuiz}%</strong><span>Kuis terbaik</span></div><div><strong>{progress.visited.filter((id) => id !== 'sun').length}/8</strong><span>Planet dipelajari</span></div></div><div className="completion-badges">{badges.filter((badge) => progress.badges.includes(badge.id)).map((badge) => <span key={badge.id} title={badge.name} aria-label={badge.name}><Icon name={badge.icon} size={26} /></span>)}</div><div className="result-actions"><button className="button secondary" onClick={() => navigate('explore')}><Icon name="telescope" />Jelajahi lagi</button><button className="button primary" onClick={() => navigate('quiz', 'challenge')}><Icon name="target" />Main Challenge</button><button className="button secondary" onClick={() => navigate('achievements')}><Icon name="trophy" />Lihat pencapaian</button></div></div>;
}