import { useState } from 'react';
import { lessons, type Lesson } from '../data/lessons';
import { useLearning } from '../state/LearningContext';
import type { Navigate, Page } from '../types';
import { GuideNote, Icon, PageHeading, PlanetOrb, ProgressBar } from '../components/ui';
import { LessonVisual } from '../components/LessonVisual';

export function MaterialsPage({ navigate, id }: { navigate: Navigate; id?: string }) {
  const { progress } = useLearning();
  const lesson = lessons.find((item) => String(item.id) === id);
  if (lesson) return <LessonDetail key={lesson.id} lesson={lesson} navigate={navigate} />;
  const guided = id === 'guided';
  return <div><PageHeading eyebrow="SATU LANGKAH, SATU PENEMUAN" title="Bekal untuk menjelajah semesta." description="Belajar lewat pengamatan, pemahaman, dan refleksi. Ikuti ritmemu sendiri." /><div className="materials-tabs"><div className="filter-tabs"><button className={!guided ? 'active' : ''} onClick={() => navigate('materials')} aria-pressed={!guided}>Semua materi</button><button className={guided ? 'active' : ''} onClick={() => navigate('materials', 'guided')} aria-pressed={guided}><Icon name="compass" size={17} />Perjalanan terarah</button></div><span className="muted">{progress.completedLessons.length} dari 7 materi selesai</span></div>{guided ? <GuidedJourney navigate={navigate} /> : <div className="materials-layout"><div className="lesson-list">{lessons.map((item) => {
    const done = progress.completedLessons.includes(item.id);
    return <button className={`lesson-row ${done ? 'done' : ''}`} key={item.id} onClick={() => navigate('materials', String(item.id))}><span className="lesson-number">{done ? <Icon name="check" size={19} /> : String(item.id).padStart(2, '0')}</span><div className="lesson-row-orb"><PlanetOrb id={item.planet} size={42} /></div><div className="lesson-row-text"><span>MATERI {item.id}</span><h2>{item.title}</h2><p>{item.subtitle}</p></div><div className="lesson-row-end"><small>{done ? 'Selesai' : '+20 XP'}</small><Icon name="right" size={19} /></div></button>;
  })}</div><aside className="learning-aside"><div className="aside-icon"><Icon name="compass" size={31} /></div><p className="eyebrow">TAHU HARUS MULAI DARI MANA?</p><h2>Astro punya rute untukmu.</h2><p>Ikuti 7 langkah yang menghubungkan materi, eksplorasi, dan tantangan.</p><button className="button secondary full-width" onClick={() => navigate('materials', 'guided')}>Mulai perjalanan terarah<Icon name="right" size={17} /></button><div className="learning-progress"><div><span>Progres belajarmu</span><strong>{Math.round(progress.completedLessons.length / 7 * 100)}%</strong></div><ProgressBar value={progress.completedLessons.length / 7 * 100} label="Progres seluruh materi" /></div><GuideNote title="Jangan hanya menghafal">Amati, tanyakan mengapa, lalu hubungkan dengan pengalaman sehari-harimu.</GuideNote></aside></div>}</div>;
}

function LessonDetail({ lesson, navigate }: { lesson: Lesson; navigate: Navigate }) {
  const { progress, completeLesson } = useLearning();
  const [reflection, setReflection] = useState(progress.reflections[lesson.id] ?? '');
  const completed = progress.completedLessons.includes(lesson.id);
  return <div className="lesson-detail"><div className="activity-topbar"><button className="back-link" onClick={() => navigate('materials')}><Icon name="left" size={17} />Semua materi</button><span>Materi {lesson.id} / 7</span></div><ProgressBar value={lesson.id / 7 * 100} label="Posisi materi" /><PageHeading eyebrow={`MATERI ${String(lesson.id).padStart(2, '0')}`} title={lesson.title} description={lesson.subtitle} /><LessonVisual lesson={lesson} /><div className="lesson-prose">{lesson.paragraphs.map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div><div className="takeaway"><span><Icon name="sparkles" size={21} /></span><div><strong>Ingat hal penting ini</strong><p>{lesson.takeaway}</p></div></div><div className="reflection-block"><div className="reflection-heading"><Icon name="moon" size={22} /><div><p className="eyebrow">JEDA SEJENAK, PIKIRKAN KEMBALI</p><h2>{lesson.reflection}</h2></div></div><label className="sr-only" htmlFor="reflection">Refleksiku tentang {lesson.title}</label><textarea id="reflection" placeholder="Tuliskan pemikiranmu dengan bahasamu sendiri..." maxLength={1500} value={reflection} onChange={(event) => setReflection(event.target.value)} rows={3} aria-describedby="reflection-help" /><small id="reflection-help">Tidak harus sempurna. Tulis sedikitnya 5 karakter untuk melanjutkan. Refleksimu tersimpan di perangkat ini.</small></div><div className="lesson-bottom"><button className="button secondary" onClick={() => navigate('materials', 'guided')}><Icon name="compass" size={18} />Lihat rute belajar</button><button className="button primary" disabled={reflection.trim().length < 5} onClick={() => { completeLesson(lesson.id, reflection); navigate(lesson.id < 7 ? 'materials' : 'quiz', lesson.id < 7 ? String(lesson.id + 1) : undefined); }}><Icon name={completed ? 'check' : 'zap'} size={18} />{completed ? 'Simpan dan lanjut' : 'Selesai & lanjut'}{!completed && <span className="button-xp">+20 XP</span>}<Icon name="right" size={17} /></button></div><a className="text-link lesson-source" href={lesson.id === 6 ? 'https://science.nasa.gov/earth/facts/' : 'https://science.nasa.gov/solar-system/solar-system-facts/'} target="_blank" rel="noreferrer">Sumber materi: NASA Science<Icon name="external" size={14} /></a></div>;
}

function GuidedJourney({ navigate }: { navigate: Navigate }) {
  const { progress } = useLearning();
  const has = (id: number) => progress.completedLessons.includes(id);
  const countPlanets = progress.visited.filter((id) => id !== 'sun').length;
  const steps: { title: string; description: string; done: boolean; page: Page; id?: string; action: string }[] = [
    { title: 'Kenali Tata Surya', description: 'Pahami keluarga besar tempat Bumi berada.', done: has(1), page: 'materials', id: '1', action: 'Buka materi pertama' },
    { title: 'Kenali Matahari', description: 'Temukan sumber cahaya dan panas kita.', done: has(2), page: 'materials', id: '2', action: 'Kenali Matahari' },
    { title: 'Kenali Planet', description: 'Selesaikan materi 3 dan 5, lalu pelajari kedelapan profil planet.', done: has(3) && has(5) && countPlanets === 8, page: !has(3) || !has(5) ? 'materials' : 'planets', id: !has(3) ? '3' : !has(5) ? '5' : undefined, action: !has(3) || !has(5) ? 'Pelajari karakteristik planet' : 'Temukan semua planet' },
    { title: 'Urutkan Planet', description: 'Selesaikan materi 4 dan tantangan menyusun planet.', done: has(4) && progress.completedGames.includes('order'), page: has(4) ? 'games' : 'materials', id: has(4) ? 'order' : '4', action: has(4) ? 'Main Urutkan Planet' : 'Pelajari urutan planet' },
    { title: 'Pelajari Rotasi & Revolusi', description: 'Pelajari gerakan Bumi pada materi 6, lalu benda langit pada materi 7.', done: has(6) && has(7), page: 'materials', id: has(6) ? '7' : '6', action: has(6) ? 'Kenali benda langit lainnya' : 'Amati gerakan Bumi' },
    { title: 'Quiz Astronaut', description: 'Gabungkan semua pemahamanmu. Raih nilai minimal 70%.', done: progress.bestQuiz >= 70, page: 'quiz', action: 'Mulai ujian astronaut' },
    { title: 'Mission Complete', description: 'Rayakan lima misi utama dan semua penemuanmu.', done: progress.missions.length === 5, page: 'complete', action: 'Lihat hasil perjalanan' },
  ];
  const active = Math.max(0, steps.findIndex((step) => !step.done));
  const allDone = steps.every((step) => step.done);
  const current = steps[allDone ? 6 : active];
  return <div className="guided-layout"><ol className="journey-steps">{steps.map((step, index) => <li key={step.title} className={`${step.done ? 'done' : ''} ${!allDone && active === index ? 'current' : ''}`}><button onClick={() => navigate(step.page, step.id)} disabled={index === 6 && !allDone}><span className="journey-dot">{step.done ? <Icon name="check" size={19} /> : index + 1}</span><span><strong>{step.title}</strong><small>{step.done ? 'Sudah selesai' : active === index ? 'Langkahmu sekarang' : 'Siap dijelajahi'}</small></span><Icon name="right" size={17} /></button></li>)}</ol><div className="journey-current"><p className="eyebrow">LANGKAH {allDone ? 7 : active + 1} / 7</p><ProgressBar value={steps.filter((step) => step.done).length / 7 * 100} label="Progres perjalanan terarah" /><div className="journey-visual"><PlanetOrb id={['earth', 'sun', 'jupiter', 'saturn', 'earth', 'neptune', 'earth'][allDone ? 6 : active]} size={142} /></div><h2>{allDone ? 'Perjalananmu lengkap!' : current.title}</h2><p>{current.description}</p><button className="button primary" onClick={() => navigate(current.page, current.id)}>{current.action}<Icon name="right" size={18} /></button><GuideNote title="Satu langkah setiap kali">Rute ini membantumu belajar dengan terarah. Kamu tetap boleh kembali dan mengeksplorasi bagian mana pun.</GuideNote></div></div>;
}