import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { orbitingPlanets, planetById, planets } from '../data/planets';
import { useLearning } from '../state/LearningContext';
import type { Navigate } from '../types';
import { GuideNote, Icon, PageHeading, PlanetOrb, SectionHeading } from '../components/ui';

export function PlanetsPage({ navigate, id }: { navigate: Navigate; id?: string }) {
  const { progress, visitPlanet } = useLearning();
  const [filter, setFilter] = useState('Semua');
  const isDetail = !!id && planets.some((planet) => planet.id === id);
  useEffect(() => { if (isDetail && id) visitPlanet(id); }, [id, isDetail, visitPlanet]);

  if (id === 'compare') return <ComparePlanets navigate={navigate} />;
  if (isDetail && id) {
    const planet = planetById(id);
    const nextPlanet = planets[(planets.indexOf(planet) + 1) % planets.length];
    return <div className="planet-detail-page"><button className="back-link" onClick={() => navigate('planets')}><Icon name="left" size={17} />Semua planet</button><div className="planet-detail-hero"><motion.div className="detail-orb-wrap" initial={{ opacity: 0, scale: 0.88 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.6 }}><div className="detail-orbit orbit-one" /><div className="detail-orbit orbit-two" /><PlanetOrb id={id} size={250} spinning /></motion.div><div className="detail-intro"><p className="eyebrow">KENALI {planet.order ? `PLANET KE-${planet.order}` : 'BINTANG KITA'}</p><h1>{planet.name}</h1><h2>{planet.tagline}</h2><p>{planet.description}</p><div className="detail-facts-inline"><span><Icon name="orbit" />{planet.order ? `Urutan ke-${planet.order}` : 'Pusat tata surya'}</span><span><Icon name="layers" />{planet.type}</span></div><button className="button secondary" onClick={() => navigate('explore', planet.id)}><Icon name="telescope" size={18} />Lihat di tata surya<Icon name="right" size={17} /></button></div></div><div className="planet-learning-content"><SectionHeading title={`Lebih dekat dengan ${planet.name}`} description="Buka satu per satu. Apa hal baru yang kamu temukan?" /><div className="planet-accordions"><details open><summary><span className="accordion-icon"><Icon name="scan" /></span><span>Ciri utama</span><Icon name="plus" /></summary><div className="accordion-body"><ul>{planet.characteristics.map((characteristic) => <li key={characteristic}>{characteristic}</li>)}</ul></div></details><details><summary><span className="accordion-icon amber"><Icon name="sparkles" /></span><span>Fakta menarik</span><Icon name="plus" /></summary><div className="accordion-body"><ul>{planet.facts.map((fact) => <li key={fact}>{fact}</li>)}</ul></div></details><details><summary><span className="accordion-icon purple"><Icon name="layers" /></span><span>Atmosfer dan jenis</span><Icon name="plus" /></summary><div className="accordion-body"><p><strong>Jenis:</strong> {planet.type}</p><p><strong>Atmosfer:</strong> {planet.atmosphere}</p></div></details></div><GuideNote title="Ayo amati bersama!">{planet.id === 'earth' ? 'Bumi adalah rumah kita. Kebiasaan kecil apa yang bisa kamu lakukan untuk merawatnya?' : `Apa yang membuat ${planet.name} berbeda dari Bumi? Coba gunakan fitur perbandingan untuk menyelidikinya.`}</GuideNote><div className="detail-bottom-actions"><a className="text-link" href={planet.source} target="_blank" rel="noreferrer">Sumber fakta: NASA Science<Icon name="external" size={15} /></a><div><button className="button secondary" onClick={() => navigate('planets', 'compare')}><Icon name="compare" size={18} />Bandingkan</button><button className="button primary" onClick={() => navigate('planets', nextPlanet.id)}>Lanjut ke {nextPlanet.name}<Icon name="right" size={18} /></button></div></div></div></div>;
  }

  const visible = planets.filter((planet) => filter === 'Semua' || planet.type === filter);
  return <div><PageHeading eyebrow="KENALI TETANGGA KOSMIKMU" title="Delapan planet. Delapan keajaiban." description="Setiap dunia punya cerita. Pilih satu dan temukan hal yang membuatnya istimewa." action={<button className="button secondary" onClick={() => navigate('planets', 'compare')}><Icon name="compare" />Bandingkan planet</button>} /><div className="filter-row"><div className="filter-tabs">{['Semua', 'Planet berbatu', 'Raksasa gas', 'Raksasa es', 'Bintang'].map((type) => <button key={type} className={filter === type ? 'active' : ''} onClick={() => setFilter(type)} aria-pressed={filter === type}>{type}</button>)}</div><span className="muted discovery-count">{progress.visited.filter((planet) => planet !== 'sun').length} / 8 planet dipelajari</span></div><div className="planet-catalog">{visible.map((planet, index) => <motion.button key={planet.id} className="planet-catalog-item" onClick={() => navigate('planets', planet.id)} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * 0.04 }}><div className="catalog-top"><span>{planet.order ? `0${planet.order}` : 'PUSAT'}</span>{progress.visited.includes(planet.id) ? <span className="discovered"><Icon name="check" size={13} />Dipelajari</span> : <span className="catalog-xp">{planet.order ? '+10 XP' : 'Bintang'}</span>}</div><div className="catalog-orb"><PlanetOrb id={planet.id} size={planet.id === 'jupiter' || planet.id === 'sun' ? 106 : 87} /></div><h2>{planet.name}</h2><span className="planet-kind">{planet.type}</span><p>{planet.tagline}</p><span className="catalog-cta">Kenali {planet.name}<Icon name="right" size={16} /></span></motion.button>)}</div><p className="scale-note"><Icon name="info" size={17} />Ilustrasi pada katalog tidak menggunakan skala ukuran yang sama. Matahari adalah bintang, bukan planet.</p></div>;
}

function ComparePlanets({ navigate }: { navigate: Navigate }) {
  const [left, setLeft] = useState('earth');
  const [right, setRight] = useState('mars');
  const a = planetById(left);
  const b = planetById(right);
  const largest = Math.max(a.diameter, b.diameter);
  const ratio = (a.diameter / b.diameter).toLocaleString('id-ID', { maximumFractionDigits: 2 });
  return <div className="compare-page"><button className="back-link" onClick={() => navigate('planets')}><Icon name="left" size={17} />Kembali ke planet</button><PageHeading eyebrow="COMPARE PLANETS" title="Serupa, tapi tak sama." description="Pilih dua planet, amati ukurannya, dan temukan perbedaannya." /><div className="comparison-selectors"><label>Planet pertama<select value={left} onChange={(event) => { const value = event.target.value; if (value === right) setRight(left); setLeft(value); }}>{orbitingPlanets.map((planet) => <option key={planet.id} value={planet.id}>{planet.name}</option>)}</select></label><button className="icon-button compare-swap" onClick={() => { setLeft(right); setRight(left); }} aria-label="Tukar kedua planet"><Icon name="compare" /></button><label>Planet kedua<select value={right} onChange={(event) => { const value = event.target.value; if (value === left) setLeft(right); setRight(value); }}>{orbitingPlanets.map((planet) => <option key={planet.id} value={planet.id}>{planet.name}</option>)}</select></label></div><div className="comparison-visual"><div><PlanetOrb id={left} size={Math.max(5, a.diameter / largest * 165)} /><h2>{a.name}</h2></div><span className="versus">VS</span><div><PlanetOrb id={right} size={Math.max(5, b.diameter / largest * 165)} /><h2>{b.name}</h2></div></div><p className="comparison-caption">Diameter {a.name} sekitar <strong>{ratio} kali</strong> diameter {b.name}. Diagram memakai perbandingan diameter yang sama, tanpa menghitung cincin.</p><div className="comparison-table" role="table" aria-label={`Perbandingan ${a.name} dengan ${b.name}`}><div role="row" className="comparison-row table-head"><span role="columnheader">Yang kita amati</span><strong role="columnheader">{a.name}</strong><strong role="columnheader">{b.name}</strong></div>{[
    ['Posisi dari Matahari', `Planet ke-${a.order}`, `Planet ke-${b.order}`],
    ['Diameter dibanding Bumi', `${(a.diameter / 12756).toLocaleString('id-ID', { maximumFractionDigits: 2 })} kali Bumi`, `${(b.diameter / 12756).toLocaleString('id-ID', { maximumFractionDigits: 2 })} kali Bumi`],
    ['Jenis planet', a.type, b.type], ['Atmosfer', a.atmosphere, b.atmosphere], ['Ciri utama', a.characteristics[0], b.characteristics[0]],
  ].map(([label, valueA, valueB]) => <div role="row" className="comparison-row" key={label}><span role="rowheader">{label}</span><span role="cell">{valueA}</span><span role="cell">{valueB}</span></div>)}</div><GuideNote title="Jeda untuk berpikir">Apa persamaan kedua planet ini? Apakah planet yang lebih besar selalu memiliki permukaan padat?</GuideNote><a className="text-link" href="https://nssdc.gsfc.nasa.gov/planetary/factsheet/" target="_blank" rel="noreferrer">Sumber ukuran: NASA Planetary Fact Sheet<Icon name="external" size={15} /></a></div>;
}