import { useState } from 'react';
import { lessons } from '../data/lessons';
import { missionDefinitions } from '../data/gamification';
import { useLearning } from '../state/LearningContext';
import type { QuizResult } from '../state/storage';
import { ResetProgress } from '../components/ResetProgress';
import { Icon, Modal, PageHeading, ProgressBar, SectionHeading } from '../components/ui';

export function TeacherPage() {
  const { progress, notify } = useLearning();
  const [resetOpen, setResetOpen] = useState(false);
  const [selectedQuiz, setSelectedQuiz] = useState<QuizResult | null>(null);

  function exportProgress() {
    const data = { application: 'Tata Surya Explorer 6', exportedAt: new Date().toISOString(), scope: 'Profil lokal pada perangkat ini', progress };
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url; link.download = `tata-surya-progres-${new Date().toISOString().slice(0, 10)}.json`;
    document.body.appendChild(link); link.click(); link.remove();
    window.setTimeout(() => URL.revokeObjectURL(url), 1000);
    notify('Laporan disiapkan', 'File JSON berisi progres dan refleksi profil lokal telah dikirim ke unduhan browser.', 'success');
  }

  return <div className="teacher-page"><PageHeading eyebrow="RUANG PENDAMPING BELAJAR" title="Mode Guru." description="Amati perkembangan, baca refleksi, dan tentukan dukungan belajar berikutnya." action={<button className="button secondary" onClick={exportProgress}><Icon name="download" size={18} />Unduh laporan</button>} /><div className="teacher-local-note"><Icon name="shield" size={22} /><p><strong>Mode lokal, tanpa akun.</strong> Data di bawah hanya milik <strong>{progress.nickname}</strong> pada browser ini, bukan data seluruh kelas. Mode ini bukan ruang admin dengan autentikasi.</p></div><div className="teacher-summary"><div><span>PROFIL AKTIF</span><strong>{progress.nickname}</strong><small>Level {progress.level} / {progress.xp} XP</small></div><div><span>PROGRES MATERI</span><strong>{progress.completedLessons.length}<small> / 7</small></strong><ProgressBar value={progress.completedLessons.length / 7 * 100} label="Materi siswa selesai" /></div><div><span>NILAI KUIS TERBAIK</span><strong>{progress.quizzes.length ? `${progress.bestQuiz}%` : '-'}</strong><small>{progress.quizzes.length} sesi tersimpan</small></div><div><span>MISI SELESAI</span><strong>{progress.missions.length}<small> / 5</small></strong><small>{progress.badges.length} badge diraih</small></div></div><SectionHeading title="Hasil belajar per materi" description="Indikator otomatis untuk pendampingan, bukan pengganti penilaian guru." /><div className="teacher-outcomes">{lessons.map((lesson) => {
    const answers = progress.quizzes.flatMap((quiz) => quiz.answers).filter((answer) => answer.lesson === lesson.id);
    const correct = answers.filter((answer) => answer.correct).length;
    const mastered = answers.length > 0 && correct / answers.length >= 0.7;
    return <details key={lesson.id} className="outcome-row"><summary><span className={`outcome-dot ${progress.completedLessons.includes(lesson.id) ? 'done' : ''}`}><Icon name={progress.completedLessons.includes(lesson.id) ? 'check' : 'book'} size={17} /></span><span><strong>{lesson.title}</strong><small>{answers.length ? `${correct} dari ${answers.length} jawaban benar pada kuis tersimpan` : 'Belum ada jawaban kuis untuk materi ini'}</small></span><span className={`outcome-status ${mastered ? 'good' : ''}`}>{answers.length ? mastered ? 'Teramati' : 'Perlu penguatan' : 'Belum diamati'}</span><Icon name="chevron-down" size={17} /></summary><div className="outcome-reflection"><strong>Refleksi siswa</strong><p>{progress.reflections[lesson.id] || 'Belum ada refleksi. Ajak siswa mengamati ilustrasi dan menuliskan pemahamannya dengan bahasanya sendiri.'}</p><small>Status materi: {progress.completedLessons.includes(lesson.id) ? 'Selesai' : 'Belum selesai'}. Refleksi tidak dinilai secara otomatis.</small></div></details>;
  })}</div><SectionHeading title="Riwayat kuis" description="Maksimal 30 sesi terakhir disimpan pada perangkat ini." />{progress.quizzes.length ? <div className="table-scroll"><table className="quiz-history"><thead><tr><th>Tanggal</th><th>Mode</th><th>Benar</th><th>Nilai</th><th>Hasil</th></tr></thead><tbody>{[...progress.quizzes].reverse().map((quiz) => <tr key={quiz.id}><td>{new Date(quiz.date).toLocaleString('id-ID', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' })}</td><td>{quiz.difficulty}</td><td>{quiz.correct}/{quiz.total}</td><td><strong className={quiz.score >= 70 ? 'text-green' : ''}>{quiz.score}%</strong></td><td><button className="text-link" onClick={() => setSelectedQuiz(quiz)}>Lihat<Icon name="right" size={15} /></button></td></tr>)}</tbody></table></div> : <div className="empty-state"><Icon name="target" size={32} /><h3>Belum ada kuis yang selesai</h3><p>Hasil akan muncul setelah siswa menyelesaikan satu sesi kuis.</p></div>}<SectionHeading title="Status misi" /><div className="teacher-missions">{missionDefinitions.map((mission) => <div key={mission.id}><Icon name={progress.missions.includes(mission.id) ? 'checks' : 'target'} size={19} /><span>{mission.name}</span><strong>{progress.missions.includes(mission.id) ? 'Selesai' : 'Belum selesai'}</strong></div>)}</div><div className="reset-section"><div><h3>Pengelolaan data lokal</h3><p>Unduh laporan sebelum mereset apabila hasil belajar masih diperlukan.</p></div><button className="button danger-outline" onClick={() => setResetOpen(true)}><Icon name="reset" size={17} />Reset data siswa</button></div><ResetProgress open={resetOpen} onClose={() => setResetOpen(false)} /><Modal open={!!selectedQuiz} onClose={() => setSelectedQuiz(null)} title="Rincian hasil kuis">{selectedQuiz && <div className="quiz-detail-modal"><p className="muted">{selectedQuiz.difficulty} / {new Date(selectedQuiz.date).toLocaleString('id-ID')}</p><div className="result-stats"><div><strong>{selectedQuiz.score}%</strong><span>Nilai akhir</span></div><div><strong>{selectedQuiz.correct}</strong><span>Benar</span></div><div><strong>{selectedQuiz.total - selectedQuiz.correct}</strong><span>Salah</span></div></div><h3>Catatan per soal</h3>{selectedQuiz.answers.map((answer, index) => <div className="quiz-answer-record" key={`${answer.questionId}-${index}`}><Icon name={answer.correct ? 'check' : 'close'} size={17} /><span>Soal {index + 1}: {lessons.find((lesson) => lesson.id === answer.lesson)?.title}</span><strong>{answer.correct ? 'Benar' : 'Perlu diulang'}</strong></div>)}</div>}</Modal></div>;
}